name: Snap Install

on:
  push:
    branches:
      - master
    paths:
      - 'snap/**'
      - '**.yml'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get-version:
      uses: emacs-eask/packaging/.github/workflows/get_version.yml@master

  build:
    needs: [get-version]
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ needs.get-version.outputs.version }}

    steps:
    - name: Install Snapcraft
      uses: samuelmeuli/action-snapcraft@v3

    - uses: actions/checkout@v6
      with:
        persist-credentials: false
        fetch-depth: 1

    - name: Prepare
      run: |
        sudo snap install multipass

    - name: Change permission
      run: |
        chmod 644 snap/snapcraft.yaml

    - name: Build Snap
      working-directory: ./snap/
      run: |
        # --destructive-mode prevents the need for Multipass/LXD
        sudo snapcraft pack --destructive-mode

    - name: Install built snap
      run: |
        sudo snap install snap/*.snap --dangerous --devmode

    - run: eask --version
